"""Classified realised-evidence candidates. Asking is never relabelled as sold."""

from __future__ import annotations

CANDIDATES = [
    {
        "name": "eBay Browse API",
        "classification": "ACTIVE_ASKING",
        "access": "official_api",
        "status": "depends_on_production_oauth",
        "docs": "https://developer.ebay.com/api-docs/buy/browse/overview.html",
        "provides": "Active listings only. Not sold evidence.",
    },
    {
        "name": "eBay Marketplace Insights item_sales/search",
        "classification": "REALIZED_SOLD",
        "access": "official_api_limited_release",
        "status": "not_entitled_403",
        "docs": "https://developer.ebay.com/api-docs/buy/marketplace-insights/resources/item_sales/methods/search",
        "provides": "Completed sales for the last 90 days if the keyset is entitled. Official endpoint is v1_beta with required category_ids. Ordinary Buy apps receive 403. Apply via Buy APIs Requirements. v1 (non-beta) is not probed.",
        "owner_action": "https://developer.ebay.com/develop/guides-v2/buy-apis-requirements",
    },
    {
        "name": "eBay Finding findCompletedItems",
        "classification": "REALIZED_SOLD",
        "access": "deprecated",
        "status": "do_not_call",
        "docs": "https://developer.ebay.com/api-docs/user-guides/static/finding-user-guide-landing.html",
        "provides": "Historical completed items. Deprecated. Not implemented.",
    },
    {
        "name": "eBay Sell Fulfillment / Finances / Analytics",
        "classification": "REALIZED_SOLD",
        "access": "user_oauth",
        "status": "implemented_awaiting_owner_consent",
        "docs": "https://developer.ebay.com/api-docs/sell/static/selling-ig-landing.html",
        "provides": "Owner-only orders and payouts after user consent. Not general market sold comps. Flow: GET /oauth/ebay/status then /oauth/ebay/start. Refresh token stored in Postgres.",
    },
    {
        "name": "eBay seller hub / Terapeak export",
        "classification": "REALIZED_SOLD",
        "access": "owner_export",
        "status": "importer_ready",
        "docs": "https://www.ebay.com/help/selling/selling-tools/terapeak-research",
        "provides": "Owner download. Parser live. Empty until the owner uploads a file.",
    },
    {
        "name": "Owner recorded sales CSV",
        "classification": "REALIZED_SOLD",
        "access": "owner_export",
        "status": "live_empty",
        "docs": "in-repo GET /sold/template and POST /import/owner-sales",
        "provides": "Highest-weight local realised evidence.",
    },
    {
        "name": "Scryfall Cardmarket EUR",
        "classification": "DEALER_RETAIL",
        "access": "official_api",
        "status": "live",
        "docs": "https://scryfall.com/docs/api",
        "provides": "Dealer/market guide. Not an Irish realised sale.",
    },
    {
        "name": "Reverb listings",
        "classification": "ACTIVE_ASKING",
        "access": "official_api",
        "status": "blocked_technical_from_this_host",
        "docs": "https://reverb.com/api",
        "provides": "Asking prices when HTTP 200. 403 from this datacentre is not scraped around.",
    },
    {
        "name": "CeX / trade-in store quotes",
        "classification": "TRADE_BUY",
        "access": "no_official_public_api",
        "status": "not_implemented",
        "docs": None,
        "provides": "Would be a liquidation floor. No official public API found; website internals are not called.",
    },
    {
        "name": "Irish auction houses (Wilsons, John Pye, Whyte's, Adams)",
        "classification": "AUCTION_HAMMER",
        "access": "no_official_public_api",
        "status": "not_implemented",
        "docs": None,
        "provides": "Hammer archives exist as HTML. No permitted structured feed found. Not scraped.",
    },
    {
        "name": "BidSpotter / i-bidder",
        "classification": "AUCTION_HAMMER",
        "access": "credentials_or_policy",
        "status": "blocked_policy",
        "docs": None,
        "provides": "Login/CAPTCHA surfaces. Not bypassed.",
    },
    {
        "name": "DoneDeal / Adverts.ie",
        "classification": "ACTIVE_ASKING",
        "access": "blocked_policy",
        "status": "blocked_policy",
        "docs": None,
        "provides": "Irish private-sale asking. No official API; not scraped.",
    },
]
